"""
07_extended_metrics.py
Extended classification + regression metrics (Tables 4.9, 4.10).
Loads from cluster_optimal_FDXXX_full.csv generated by 06_shap_analysis.py.
"""

import sys
import time
from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.metrics import f1_score, precision_score, recall_score, accuracy_score

ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(ROOT))
from cmapss.config import RESULTS_DIR, SUBSETS

_PRED_DIR = RESULTS_DIR / "predictions"
_TAB_DIR  = RESULTS_DIR / "tables"

NEAR_FAILURE_THR = 30
THRESHOLD_GRID   = [30, 40, 50, 60]


def _load_last_cycle(subset: str) -> pd.DataFrame:
    cache = _PRED_DIR / f"cluster_optimal_{subset}_full.csv"
    if not cache.exists():
        raise FileNotFoundError(f"Run 06_shap_analysis.py first to generate {cache.name}")
    df = pd.read_csv(cache)
    lc = df[df["is_last_cycle"] == 1].copy()
    lc["y_true"] = lc["y_true_unclipped"]
    return lc


def _r2(y_true, y_pred):
    ss_res = np.sum((y_true - y_pred) ** 2)
    ss_tot = np.sum((y_true - y_true.mean()) ** 2)
    return float(1.0 - ss_res / ss_tot) if ss_tot > 0 else 0.0


def _binary_metrics(y_true, y_pred, thr):
    yc = (y_true < thr).astype(int)
    pc = (y_pred < thr).astype(int)
    return {
        "f1":        float(f1_score(yc, pc, zero_division=0)),
        "precision": float(precision_score(yc, pc, zero_division=0)),
        "recall":    float(recall_score(yc, pc, zero_division=0)),
        "acc":       float(accuracy_score(yc, pc)),
    }


def compute_extended_metrics(lc: pd.DataFrame) -> dict:
    y_true = lc["y_true"].values
    yp     = lc["y_pred_pseudo"].values
    yt     = lc["y_pred_true"].values

    mp = _binary_metrics(y_true, yp, NEAR_FAILURE_THR)
    mt = _binary_metrics(y_true, yt, NEAR_FAILURE_THR)

    return {
        "R2_pseudo":               round(_r2(y_true, yp), 4),
        "R2_true":                 round(_r2(y_true, yt), 4),
        "MAE_pseudo":              round(float(np.mean(np.abs(y_true - yp))), 4),
        "MAE_true":                round(float(np.mean(np.abs(y_true - yt))), 4),
        "F1_pseudo":               round(mp["f1"],        4),
        "F1_true":                 round(mt["f1"],        4),
        "precision_pseudo":        round(mp["precision"], 4),
        "precision_true":          round(mt["precision"], 4),
        "recall_pseudo":           round(mp["recall"],    4),
        "recall_true":             round(mt["recall"],    4),
        "acc_within_10_pseudo":    round(float(np.mean(np.abs(y_true - yp) <= 10) * 100), 2),
        "acc_within_10_true":      round(float(np.mean(np.abs(y_true - yt) <= 10) * 100), 2),
        "near_failure_acc_pseudo": round(mp["acc"] * 100, 2),
        "near_failure_acc_true":   round(mt["acc"] * 100, 2),
    }


def compute_threshold_sensitivity(lc: pd.DataFrame, subset: str) -> list:
    y_true = lc["y_true"].values
    yp     = lc["y_pred_pseudo"].values
    yt     = lc["y_pred_true"].values
    rows   = []
    for thr in THRESHOLD_GRID:
        yc = (y_true < thr).astype(int)
        pp = (yp     < thr).astype(int)
        pt = (yt     < thr).astype(int)
        rows.append({
            "subset":           subset,
            "threshold":        thr,
            "F1_pseudo":        round(float(f1_score(yc, pp, zero_division=0)),        4),
            "F1_true":          round(float(f1_score(yc, pt, zero_division=0)),        4),
            "precision_pseudo": round(float(precision_score(yc, pp, zero_division=0)), 4),
            "precision_true":   round(float(precision_score(yc, pt, zero_division=0)), 4),
            "recall_pseudo":    round(float(recall_score(yc, pp, zero_division=0)),    4),
            "recall_true":      round(float(recall_score(yc, pt, zero_division=0)),    4),
        })
    return rows


if __name__ == "__main__":
    t0 = time.perf_counter()
    _TAB_DIR.mkdir(parents=True, exist_ok=True)

    rows49  = []
    rows410 = []

    for subset in SUBSETS:
        lc = _load_last_cycle(subset)
        rows49.append({"subset": subset, **compute_extended_metrics(lc)})
        rows410.extend(compute_threshold_sensitivity(lc, subset))

    df49  = pd.DataFrame(rows49)
    df410 = pd.DataFrame(rows410)

    df49.to_csv( _TAB_DIR / "table_4_9_extended_metrics.csv",       index=False)
    df410.to_csv(_TAB_DIR / "table_4_10_threshold_sensitivity.csv",  index=False)
    print("Saved: table_4_9_extended_metrics.csv")
    print("Saved: table_4_10_threshold_sensitivity.csv")

    # ── Console summary Table 4.9 ────────────────────────────────────────────────
    print("\nTable 4.9 — Extended Metrics Summary")
    hdr = (f"{'Subset':<8} {'R2_p':>7} {'R2_t':>7} {'MAE_p':>7} {'MAE_t':>7} "
           f"{'F1_p':>7} {'F1_t':>7} {'acc10_p':>8} {'acc10_t':>8} {'nf_p%':>7} {'nf_t%':>7}")
    print(hdr)
    print("-" * 85)
    for _, r in df49.iterrows():
        print(
            f"{r['subset']:<8} {r['R2_pseudo']:>7.4f} {r['R2_true']:>7.4f} "
            f"{r['MAE_pseudo']:>7.2f} {r['MAE_true']:>7.2f} "
            f"{r['F1_pseudo']:>7.4f} {r['F1_true']:>7.4f} "
            f"{r['acc_within_10_pseudo']:>8.2f} {r['acc_within_10_true']:>8.2f} "
            f"{r['near_failure_acc_pseudo']:>7.2f} {r['near_failure_acc_true']:>7.2f}"
        )

    # ── Threshold sensitivity: best F1 per subset ────────────────────────────────
    print("\nThreshold sensitivity — best F1_pseudo per subset:")
    print(f"{'Subset':<8} {'Best_thr':>9} {'F1_pseudo':>10} {'F1_true':>10}")
    print("-" * 42)
    for subset in SUBSETS:
        sub  = df410[df410["subset"] == subset]
        best = sub.loc[sub["F1_pseudo"].idxmax()]
        print(f"{subset:<8} {int(best['threshold']):>9} {best['F1_pseudo']:>10.4f} {best['F1_true']:>10.4f}")

    # ── Sanity checks ────────────────────────────────────────────────────────────
    print("\n-- Sanity Check --")
    for _, r in df49.iterrows():
        r2t_ok = r["R2_true"]   > 0.5
        r2p_ok = 0.30 <= r["R2_pseudo"] <= 0.55
        print(f"{r['subset']}: R2_true={r['R2_true']:.4f} {'PASS' if r2t_ok else 'FAIL'}>0.5  |  R2_pseudo={r['R2_pseudo']:.4f} {'PASS' if r2p_ok else 'WARN'}[0.30,0.55]")

    fd1_f1p = df49[df49["subset"] == "FD001"]["F1_pseudo"].iloc[0]
    print(f"FD001 F1_pseudo@30: {fd1_f1p:.4f}  (expected near 0 — RUL ceiling effect)  {'PASS' if fd1_f1p < 0.20 else 'WARN'}")

    print(f"\nTotal runtime: {time.perf_counter()-t0:.1f}s")

