"""
08_bias_calibration.py
One-sample t-tests for prediction bias + isotonic regression calibration (Tables 4.12, 4.13).
Loads from cluster_optimal_FDXXX_full.csv generated by 06_shap_analysis.py.
"""

import sys
import time
from pathlib import Path

import numpy as np
import pandas as pd
from scipy.stats import ttest_1samp
from sklearn.isotonic import IsotonicRegression
from sklearn.model_selection import KFold

ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(ROOT))
from cmapss.config import RESULTS_DIR, SUBSETS

_PRED_DIR = RESULTS_DIR / "predictions"
_TAB_DIR  = RESULTS_DIR / "tables"


def _load_last_cycle(subset: str) -> pd.DataFrame:
    cache = _PRED_DIR / f"cluster_optimal_{subset}_full.csv"
    if not cache.exists():
        raise FileNotFoundError(f"Run 06_shap_analysis.py first to generate {cache.name}")
    df = pd.read_csv(cache)
    lc = df[df["is_last_cycle"] == 1].copy()
    lc["y_true"] = lc["y_true_unclipped"]
    return lc


def _rmse(a, b):
    return float(np.sqrt(np.mean((a - b) ** 2)))


def bias_tests_for_subset(lc: pd.DataFrame, subset: str) -> list:
    y_true = lc["y_true"].values
    errors = lc["y_pred_pseudo"].values - y_true

    zones = [
        ("overall",      np.ones(len(y_true), dtype=bool)),
        ("early_mid",    y_true >= 50),
        ("near_failure", y_true <  50),
    ]

    rows = []
    for zone_name, mask in zones:
        err = errors[mask]
        n   = int(mask.sum())
        if n < 2:
            rows.append({
                "subset": subset, "zone": zone_name, "n": n,
                "mean_error": np.nan, "sd_error": np.nan,
                "t_stat": np.nan, "p_value": np.nan, "significant": False,
            })
            continue
        t_stat, p_val = ttest_1samp(err, 0)
        rows.append({
            "subset":      subset,
            "zone":        zone_name,
            "n":           n,
            "mean_error":  round(float(err.mean()),       4),
            "sd_error":    round(float(err.std(ddof=1)),  4),
            "t_stat":      round(float(t_stat),           4),
            "p_value":     round(float(p_val),            6),
            "significant": bool(p_val < 0.05),
        })
    return rows


def isotonic_calibration(lc: pd.DataFrame) -> dict:
    y_true = lc["y_true"].values
    y_pred = lc["y_pred_pseudo"].values
    n      = len(y_true)

    kf      = KFold(n_splits=5, shuffle=True, random_state=42)
    y_calib = np.zeros(n)
    for tr_idx, val_idx in kf.split(y_pred):
        iso = IsotonicRegression(out_of_bounds="clip")
        iso.fit(y_pred[tr_idx], y_true[tr_idx])
        y_calib[val_idx] = iso.predict(y_pred[val_idx])

    nf_mask     = y_true < 50
    bias_before = float(np.mean(y_pred[nf_mask]   - y_true[nf_mask])) if nf_mask.any() else np.nan
    bias_after  = float(np.mean(y_calib[nf_mask]  - y_true[nf_mask])) if nf_mask.any() else np.nan
    bias_red    = (abs(bias_before) - abs(bias_after)) / abs(bias_before) * 100 if bias_before else np.nan

    r_before = _rmse(y_true, y_pred)
    r_after  = _rmse(y_true, y_calib)

    return {
        "RMSE_before":              round(r_before,    4),
        "RMSE_after":               round(r_after,     4),
        "delta_RMSE":               round(r_before - r_after, 4),
        "near_failure_bias_before": round(bias_before, 4),
        "near_failure_bias_after":  round(bias_after,  4),
        "bias_reduction_pct":       round(bias_red,    2),
    }


if __name__ == "__main__":
    t0 = time.perf_counter()
    _TAB_DIR.mkdir(parents=True, exist_ok=True)

    rows412 = []
    rows413 = []

    for subset in SUBSETS:
        lc = _load_last_cycle(subset)
        rows412.extend(bias_tests_for_subset(lc, subset))
        rows413.append({"subset": subset, **isotonic_calibration(lc)})

    df412 = pd.DataFrame(rows412)
    df413 = pd.DataFrame(rows413)

    df412.to_csv(_TAB_DIR / "table_4_12_bias_tests.csv",           index=False)
    df413.to_csv(_TAB_DIR / "table_4_13_isotonic_calibration.csv", index=False)
    print("Saved: table_4_12_bias_tests.csv")
    print("Saved: table_4_13_isotonic_calibration.csv")

    # ── Console: Table 4.12 ──────────────────────────────────────────────────────
    print("\nTable 4.12 — Bias t-tests (Pseudo Model)")
    print(f"{'Subset':<8} {'Zone':<14} {'n':>5} {'Mean_err':>10} {'SD':>8} {'t':>8} {'p':>9} {'Sig':>4}")
    print("-" * 75)
    for _, r in df412.iterrows():
        print(
            f"{r['subset']:<8} {r['zone']:<14} {r['n']:>5} {r['mean_error']:>10.2f} "
            f"{r['sd_error']:>8.2f} {r['t_stat']:>8.3f} {r['p_value']:>9.6f} "
            f"{'YES' if r['significant'] else 'NO':>4}"
        )

    # ── Console: Table 4.13 ──────────────────────────────────────────────────────
    print("\nTable 4.13 — Isotonic Calibration (Pseudo Model)")
    print(f"{'Subset':<8} {'RMSE_bef':>10} {'RMSE_aft':>10} {'dRMSE':>7} {'Bias_bef':>10} {'Bias_aft':>10} {'Red%':>7}")
    print("-" * 68)
    for _, r in df413.iterrows():
        print(
            f"{r['subset']:<8} {r['RMSE_before']:>10.4f} {r['RMSE_after']:>10.4f} "
            f"{r['delta_RMSE']:>7.4f} {r['near_failure_bias_before']:>10.2f} "
            f"{r['near_failure_bias_after']:>10.2f} {r['bias_reduction_pct']:>7.1f}%"
        )

    # ── Sanity checks ────────────────────────────────────────────────────────────
    print("\n-- Sanity Check --")
    nf_rows = df412[df412["zone"] == "near_failure"]
    for _, r in nf_rows.iterrows():
        bias_ok = 28.2 <= r["mean_error"] <= 39.9
        sig_ok  = r["significant"]
        print(
            f"{r['subset']}: near_fail mean_err={r['mean_error']:.2f} "
            f"{'PASS' if bias_ok else 'WARN'}[28.2,39.9]  sig={'PASS' if sig_ok else 'FAIL'}"
        )
    for _, r in df413.iterrows():
        red_ok   = 38 <= r["bias_reduction_pct"] <= 62
        drmse_ok = 0.0 <= r["delta_RMSE"]
        print(
            f"{r['subset']}: delta_RMSE={r['delta_RMSE']:.4f} {'PASS' if drmse_ok else 'FAIL'}>0  "
            f"bias_red={r['bias_reduction_pct']:.1f}% {'PASS' if red_ok else 'WARN'}[38,62]"
        )

    print(f"\nTotal runtime: {time.perf_counter()-t0:.1f}s")

