"""
09_naive_baselines.py
Naive baseline comparison vs cluster pipeline pseudo RMSE (Table 4.11).
Loads from cluster_optimal_FDXXX_full.csv generated by 06_shap_analysis.py.
"""

import sys
import time
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(ROOT))
from cmapss.config import RESULTS_DIR, SUBSETS

_PRED_DIR = RESULTS_DIR / "predictions"
_TAB_DIR  = RESULTS_DIR / "tables"


def _load_last_cycle(subset: str) -> pd.DataFrame:
    cache = _PRED_DIR / f"cluster_optimal_{subset}_full.csv"
    if not cache.exists():
        raise FileNotFoundError(f"Run 06_shap_analysis.py first to generate {cache.name}")
    df = pd.read_csv(cache)
    lc = df[df["is_last_cycle"] == 1].copy()
    lc["y_true"] = lc["y_true_unclipped"]
    return lc


def _rmse(y_true, y_pred):
    return float(np.sqrt(np.mean((y_true - y_pred) ** 2)))


if __name__ == "__main__":
    t0 = time.perf_counter()
    _TAB_DIR.mkdir(parents=True, exist_ok=True)

    rows = []
    for subset in SUBSETS:
        lc     = _load_last_cycle(subset)
        y_true = lc["y_true"].values
        y_pred = lc["y_pred_pseudo"].values

        mean_r   = _rmse(y_true, np.full_like(y_true, y_true.mean()))
        median_r = _rmse(y_true, np.full_like(y_true, np.median(y_true)))
        const_r  = _rmse(y_true, np.full_like(y_true, 60.0))
        pseudo_r = _rmse(y_true, y_pred)

        rows.append({
            "subset":                    subset,
            "mean_rmse":                 round(mean_r,   4),
            "median_rmse":               round(median_r, 4),
            "const60_rmse":              round(const_r,  4),
            "pseudo_rmse":               round(pseudo_r, 4),
            "improvement_vs_mean_pct":   round((mean_r   - pseudo_r) / mean_r   * 100, 2),
            "improvement_vs_median_pct": round((median_r - pseudo_r) / median_r * 100, 2),
            "improvement_vs_const_pct":  round((const_r  - pseudo_r) / const_r  * 100, 2),
        })

    df411 = pd.DataFrame(rows)
    df411.to_csv(_TAB_DIR / "table_4_11_naive_baselines.csv", index=False)
    print("Saved: table_4_11_naive_baselines.csv")

    # ── Console ──────────────────────────────────────────────────────────────────
    print("\nTable 4.11 — Naive Baseline Comparison")
    hdr = (f"{'Subset':<8} {'Mean':>10} {'Median':>10} {'Const60':>10} {'Pseudo':>10} "
           f"{'vs_Mean%':>10} {'vs_Med%':>9} {'vs_C60%':>9}")
    print(hdr)
    print("-" * 82)
    for _, r in df411.iterrows():
        print(
            f"{r['subset']:<8} {r['mean_rmse']:>10.4f} {r['median_rmse']:>10.4f} "
            f"{r['const60_rmse']:>10.4f} {r['pseudo_rmse']:>10.4f} "
            f"{r['improvement_vs_mean_pct']:>10.2f} {r['improvement_vs_median_pct']:>9.2f} "
            f"{r['improvement_vs_const_pct']:>9.2f}"
        )

    # ── Sanity check ─────────────────────────────────────────────────────────────
    print("\n-- Sanity Check --")
    all_beat = all(
        r["pseudo_rmse"] < min(r["mean_rmse"], r["median_rmse"], r["const60_rmse"])
        for _, r in df411.iterrows()
    )
    print(f"Pseudo outperforms all 3 baselines for all subsets: {'PASS' if all_beat else 'FAIL'}")
    for _, r in df411.iterrows():
        ok = 15 <= r["improvement_vs_mean_pct"] <= 40
        print(f"  {r['subset']}: improvement_vs_mean={r['improvement_vs_mean_pct']:.2f}%  {'PASS' if ok else 'WARN'}[15,40]")

    print(f"\nTotal runtime: {time.perf_counter()-t0:.1f}s")

